### PR TITLE
Update 18Kaas and 1849

### PR DESCRIPTION
**Pull request by knauman**

### CODE REVIEW

**Comment by knauman** [comment]
When I run a validate on the games I don't receive any errors. I'm not sure what the conflicts are.

**Comment by kelsin** [comment]
Github is saying there are conflicts between your branch and 1849 and 18Kaas (on this PR page), Is your branch on top of the latest master? I can help look later if you can't find it.

**Comment by knauman** [comment]
No idea, The only games I'm still receiving validate errors on are 1844, 18C2C, and 18Rhl.

**Comment by kelsin** [comment]
Uggg... close this for now since all of these games are not public games. Sorry.

**Pull request closed without merging**
