### PR TITLE
Add 1891

### PR DESCRIPTION
**Pull request by ventusignis**
I've taken my physical copy of 1891 and used it to put this together. 
Since the Japanese National Railway has 12(!) tokens, I decided to try something different - not sure if this is OK or not.
What I did was for the JNR, it has 1 token with a cost of "12 x 100 Yen" and I added 11 "JNR" tokens to the "tokens" list. This way the JNR charter isn't overflowing with token markers, but depending on how the tokens in the companies are used (Thinking of 18xx.games in particular) there may, or may not be an issue with that

### CODE REVIEW

**Comment by ventusignis** [comment]
I have 2 concerns:
1 - The automated test failed 1891 because some of the map hexes use the "mountain" attribute; When I was running 18xx-maker locally I was able to use that property to get mountains on the tile - is this the test job giving a false failure, or do I need to use a different way to represent the mountains?
2 - Is the Hiroshima hex too busy?
image

**Comment by kelsin** [comment]
lol the hex being busy is all up to opinion :) Looks like you made due with what you need to do. I have no problems with it and you can always edit and change things later as you see fit.

Don't worry too much about what 18xx.games accepts and doesn't. As features come in we'll make changes and use schemas to try and find games that break the new ways and edit them.

As far as mountains: yeah that way is old. Instead of `"mountain": {...}` you want to use `"terrain": [{"type": "mountain", ...}]`

It still "works" but is deprecated and I will be removing that code at some point.

**Comment by ventusignis** [comment]
@kelsin I've fixed up the branch and finished proofreading the map, I'd be happy to have this merged if you are

**Comment by ventusignis** [comment]
1891 is ready now

**Pull request merged**
